name: Tests
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install python dependencies
              run: |
                  pip install pycryptodome

            - name: Install php
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: openssl

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Install Node.js dependencies
              run: |
                  npm install crypto-js --save --working-dir=encryption

            - name: Install Java
              uses: actions/setup-java@v2
              with:
                  distribution: "adopt"
                  java-version: "11"

            - name: Install org.json
              run: |
                  wget https://repo1.maven.org/maven2/org/json/json/20240303/json-20240303.jar
                  mkdir lib
                  mv json-20240303.jar lib/org.json.jar

            - name: Install Dotnet (C#)
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "6.0.x"

            - name: Install Dotnet Script
              run: dotnet tool install -g dotnet-script

            - name: Install Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.3"

            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.22"

            - name: Run tests
              run: |
                  php test.php
