name: Tests
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install python dependencies
              run: |
                  pip install pycryptodome

            - name: Install php
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: openssl

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Run tests
              run: |
                  php test.php
